#!/usr/bin/env python
"""usage: {} FILENAME
"""

import sys

from codegen import Codegen
from lexer import lex
from parser import Parser, ParserError


def main(args):
    try:
        filename = args[1]

        with open(filename) as file_:
            code = file_.read()
    except IndexError:
        sys.stderr.write(__doc__.format(args[0]))
        return 1
    except IOError:
        sys.stderr.write("error: cannot open '{}'\n".format(filename))
        return 1

    success, tokens = lex(code)

    if not success:
        sys.stderr.write("error: " + tokens)
        return 1

    try:
        codegen = Codegen(Parser(tokens))
        module = codegen.gen_module(main=True)
        exec compile(module, filename, "exec") in globals()
    except ParserError as e:
        sys.stderr.write("error: {}\n".format(e))
        return 1

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
