#!/usr/bin/env python
"""usage: {} FILENAME
"""

import sys
import lexer
import parser


def main(args):
    try:
        filename = args[1]

        with open(filename) as file_:
            code = file_.read()
    except IndexError:
        sys.stderr.write(__doc__.format(args[0]))
        return 1
    except IOError:
        sys.stderr.write("error: cannot open '{}'\n".format(filename))
        return 1

    success, tokens = lexer.lex(code)

    if not success:
        sys.stderr.write("error: " + tokens)
        return 1

    nodes = parser.Parser(tokens).parse()

    for node in nodes:
        if node is not None:
            parser.print_tree(node)

    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv))
